In [14]:
import pandas as pd

#Baca data dari file excel 
df_jabar = pd.read_excel('disperkim-od_16985_jumlah_produksi_sampah_berdasarkan_kabupatenkota_v3_data.xlsx', sheet_name='data')
df_jabar

,id,kode_provinsi,nama_provinsi,kode_kabupaten_kota,nama_kabupaten_kota,jumlah_produksi_sampah,satuan,tahun
0,1,32,JAWA BARAT,3201,KABUPATEN BOGOR,1511.15,TON PER HARI,2015
1,2,32,JAWA BARAT,3202,KABUPATEN SUKABUMI,419.01,TON PER HARI,2015
2,3,32,JAWA BARAT,3203,KABUPATEN CIANJUR,981.41,TON PER HARI,2015
3,4,32,JAWA BARAT,3204,KABUPATEN BANDUNG,1895.94,TON PER HARI,2015
4,5,32,JAWA BARAT,3205,KABUPATEN GARUT,464.74,TON PER HARI,2015
...,...,...,...,...,...,...,...,...
184,185,32,JAWA BARAT,3275,KOTA BEKASI,1500.77,TON PER HARI,2021
185,186,32,JAWA BARAT,3276,KOTA DEPOK,1418.87,TON PER HARI,2021
186,187,32,JAWA BARAT,3277,KOTA CIMAHI,193.36,TON PER HARI,2021
187,188,32,JAWA BARAT,3278,KOTA TASIKMALAYA,295.87,TON PER HARI,2021
188,189,32,JAWA BARAT,3279,KOTA BANJAR,60.29,TON PER HARI,2021

In [17]:
df_sampah = pd.DataFrame(df_jabar, columns=['nama_kabupaten_kota','jumlah_produksi_sampah','tahun'])
df_sampah

df_sampah.to_csv('data_sampah.csv')
df_sampah.to_excel('data_sampah.xlsx')

In [18]:
#no.2
import numpy as np

d15 ={} #jumlah sampah pada tahun 2015

for i , row in df_sampah.iterrows():
    tahun = row['tahun']
    sampah = row['jumlah_produksi_sampah']

    if tahun == 2015 not in d15 :
        d15[tahun] = sampah
    elif tahun == 2015 in d15 :
        d15[tahun] += sampah
print  ('=============== Data Tahun 2015 ===============')
for i,j in d15.items():
    print(f"Jumlah sampah pada tahun {i} adalah {j:.2f} ton")
    
df_t2015 = pd.DataFrame ([
    {'Tahun':i,'Total/tahun':j}
    for i,j in d15.items()
])

df_t2015

df_t2015.to_csv('df_t2015.csv')
df_t2015.to_excel('df_t2015.xlsx')

=============== Data Tahun 2015 ===============
Jumlah sampah pada tahun 2015 adalah 20969.27 ton

In [19]:
#NO.3

thn = {}

for i,j in df_sampah.iterrows():
     tahun = j['tahun']
     tsampah = j['jumlah_produksi_sampah']
     
     if tahun not in thn:
          thn[tahun] = tsampah 
     else :
          thn[tahun] += tsampah

print  ('=============== Data per tahun ==================')         
for i,j in thn.items():
     print(f'Pada tahun {i} terdapat {j:.2f} ton sampah')

df_sampahthn = pd.DataFrame([
   {'Tahun':i,'Total Sampah':j}
   for i,j in thn.items()
])

df_sampahthn

df_sampahthn.to_csv('df_sampahthn.csv')
df_sampahthn.to_excel('df_sampahthn.xlsx')

=============== Data per tahun ==================
Pada tahun 2015 terdapat 20969.27 ton sampah
Pada tahun 2016 terdapat 20969.27 ton sampah
Pada tahun 2017 terdapat 20969.27 ton sampah
Pada tahun 2018 terdapat 22772.92 ton sampah
Pada tahun 2019 terdapat 24490.56 ton sampah
Pada tahun 2020 terdapat 25333.00 ton sampah
Pada tahun 2021 terdapat 15735.36 ton sampah

In [20]:
#NO.4

tkk = {}

for i,j in df_sampah.iterrows():
     daerah = j['nama_kabupaten_kota']
     sampah = j['jumlah_produksi_sampah']
     
     if daerah not in tkk : 
          tkk[daerah] = sampah
     else : 
          tkk[daerah] += sampah
print  ('=============== Data per Daerah ===============')
for i,j in tkk.items():
     print(f'Pada daerah {i} terdapat {j:.2f} ton sampah')
     
df_sampahdaerah = pd.DataFrame([
     {'Nama Kabupaten/Kota':i,'Total Sampah':j}
     for i,j in tkk.items()
])
df_sampahdaerah

df_sampahdaerah.to_csv('df_sampahdaerah.csv')
df_sampahdaerah.to_excel('df_sampahdaerah.xlsx')

=============== Data per Daerah ===============
Pada daerah KABUPATEN BOGOR terdapat 13113.49 ton sampah
Pada daerah KABUPATEN SUKABUMI terdapat 4038.19 ton sampah
Pada daerah KABUPATEN CIANJUR terdapat 6497.92 ton sampah
Pada daerah KABUPATEN BANDUNG terdapat 11934.04 ton sampah
Pada daerah KABUPATEN GARUT terdapat 4484.29 ton sampah
Pada daerah KABUPATEN TASIKMALAYA terdapat 3531.33 ton sampah
Pada daerah KABUPATEN CIAMIS terdapat 2329.72 ton sampah
Pada daerah KABUPATEN KUNINGAN terdapat 2486.63 ton sampah
Pada daerah KABUPATEN CIREBON terdapat 3205.17 ton sampah
Pada daerah KABUPATEN MAJALENGKA terdapat 2593.39 ton sampah
Pada daerah KABUPATEN SUMEDANG terdapat 2532.71 ton sampah
Pada daerah KABUPATEN INDRAMAYU terdapat 5383.18 ton sampah
Pada daerah KABUPATEN SUBANG terdapat 4735.53 ton sampah
Pada daerah KABUPATEN PURWAKARTA terdapat 2262.90 ton sampah
Pada daerah KABUPATEN KARAWANG terdapat 5997.44 ton sampah
Pada daerah KABUPATEN BEKASI terdapat 11328.27 ton sampah
Pada daerah KABUPATEN BANDUNG BARAT terdapat 4972.37 ton sampah
Pada daerah KABUPATEN PANGANDARAN terdapat 1277.55 ton sampah
Pada daerah KOTA BOGOR terdapat 5952.47 ton sampah
Pada daerah KOTA SUKABUMI terdapat 1833.73 ton sampah
Pada daerah KOTA BANDUNG terdapat 14521.78 ton sampah
Pada daerah KOTA CIREBON terdapat 1887.57 ton sampah
Pada daerah KOTA BEKASI terdapat 15504.31 ton sampah
Pada daerah KOTA DEPOK terdapat 12209.61 ton sampah
Pada daerah KOTA CIMAHI terdapat 3112.35 ton sampah
Pada daerah KOTA TASIKMALAYA terdapat 2754.78 ton sampah
Pada daerah KOTA BANJAR terdapat 758.93 ton sampah